services:
  - type: web
    name: buganda-backend
    env: node
    region: ohio
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        scope: run
        sync: false
      - key: PORT
        value: 10000
  
  - type: static_site
    name: buganda-frontend
    env: static
    region: ohio
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - path: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://buganda-backend.onrender.com
